#!/bin/bash

set -e

cd "$(dirname "$0")/.."

echo "Updating raspi-ir-mpdc service..."

if [ -e /etc/raspi-ir-mpdc.conf ]
  then
    read -p "Overwrite existing configuration file '/etc/raspi-ir-mpdc.conf' (y/N)?" ov
  else
    ov="y"
fi

if [ "$ov" == "y" -o "$ov" == "Y" ]
  then
    sudo cp raspi-ir-mpdc.conf /etc
fi

echo "Updating service script '/usr/local/bin/raspi-ir-mpdc.py' (temporarily stopping service)"
sudo systemctl stop raspi-ir-mpdc

sudo cp -u raspi-ir-mpdc.py /usr/local/bin/
sudo chmod +x /usr/local/bin/raspi-ir-mpdc.py

sudo cp -u raspi-ir-mpdc.service /lib/systemd/system

echo "Restarting raspi-ir-mpdc service..."
sudo systemctl daemon-reload
sudo systemctl start raspi-ir-mpdc
sleep 3
systemctl status raspi-ir-mpdc

echo "raspi-ir-mpdc service updated."
